name: ci-template-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Downloads repo to the machine
      - uses: actions/setup-go@v4 # Prepare machine to run go
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
