name: ci-template-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21.6, 1.22]
    steps:
      - uses: actions/checkout@v4 # Downloads repo to the machine
      - uses: actions/setup-go@v4 # Prepare machine to run go
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go
